### ISSUE TITLE
Not workig with newer versions

### ISSUE THREAD

**Issue by kabelja5** [jsliacan/flagmatic#1]
To work with newer versions there has to be commented out or deleted 

32 from sage.rings.arith import binomial
33 from sage.combinat.all import Tuples, Combinations
34 from sage.rings.all import Integer, RationalField

in file lib/python2.7/dist-packages/flagmatic/random_graph_construction.py
after instalation

as those packages are already as functions in sage.

**Comment by jsliacan** [comment]
Thanks, I got another person having a problem with this on Ubuntu 16.04LTS, Sage-8.6. However, on an OSX 10.14.2, Sage-8.6, my flagmatic imports nicely with those lines in there. Any guess what's going on? Thanks.

**Comment by kabelja5** [comment]
Hi,
I do not know if I can help you. I was just adding this lib to sage for my brother and got stuck upon this problem. So I though it can help someone else. Otherwise as I read a lot about that during the fixing I learnt that the errors that shows if you just write import of the lib to terminal of sage in ubuntu it gives a really good description. So if you need help post that error.

**Comment by jsliacan** [comment]
It would seem that I just forgot to update one line of imports in the random_graph_construction.py (as random_tournament_construction.py wasn't throwing errors). Functions like binomial used to be in 
`sage.rings.arith` and are now in `sage.arith.all`. I think this might have been what was causing problems. Anyways, thanks for your time!

**Comment by jsliacan** [comment]
Addressed in #2, closing.
